<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="css/normalize.css" />
		<link rel
		="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Amaranth|Open+Sans" rel="stylesheet"> 
		<link rel="stylesheet" href="css/main.css" />
		<title>Banana Store</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li> <a href="home.php"> <img src="../views/img/popLogo.png" alt="bananaStore"> </a> </li>
					
					
					<li> 
						<a href="panier.php" id="panier"><span> Mon panier </span> <i class="fas fa-shopping-cart"></i> 
					<?php $ProductCartNumber = count($_SESSION['cart']);
					echo $ProductCartNumber ;
					?>
						</a> 
					</li>
					
				</ul>
				<div id="connexion">
					<?php if (isset($_SESSION['iduser'])): ?>
			
					<?php
						$me = getUserById($_SESSION['iduser']);
					?>
					Bonjour <?= $me['firstname'] ?> <?= $me['lastname'] ?>
					<a href="logout.php">Se déconnecter</a>

					<?php else: ?>
					
					<a href="login.php">S'identifier</a>

					<?php endif; ?>
				</div>
			</nav>

		
		</header>
		