<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="css/normalize.css" />
		<link rel="stylesheet" href="css/main.css" />
		<title>Banana Store</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li> <a href="home.php"> Accueil</a> </li>
					<?php 
					if (isset($_SESSION['id']) AND isset($_SESSION['email'])){

        				echo "Bonjour {$_SESSION['firstname']} {$_SESSION['lastname']}";
        				// pre($_SESSION);
        				// exit;
        				

					} else{
						echo "</a><li> <a href='login.php'> Se connecter</a> </li>";
					}

					?>

				</ul>
			</nav>

		
		</header>
		