<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="css/normalize.css" />
		<link rel="stylesheet" href="css/main.css" />
		<title>Banana Store</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li> <a href="home.php"> Accueil</a> </li>
				</ul>
			</nav>

		<form method="POST" action="login.php">
			<label for="login"></label>
			<input type="text" name="login" id="login" placeholder="Votre mail">
			<button>Recherchez</button>
		</form>
		</header>
		