<?php 
include '../views/header.phtml'; 
?>

<main>
	<form method="GET" action="resultList.php">
		<label for="research"></label>
		<input type="text" name="research" id="research" placeholder="Votre Recherche">
		<button>Recherchez</button>
	</form>


	<section>
		<h2> Les jolies figurines </h2>
		<?php foreach ($productsList as $product): ?>
		<div class="product">
			<img src="<?= $product["photo"] ?>">	
			<p class="name"><?= $product["name"] ?></p>
			<p class="description"><?= $product["description"] ?></p>
			<p class="price"><?= $product["price"] ?>€</p>
		</div>
		<?php endforeach; ?>
	</section>

</main>

<?php 
include '../views/footer.phtml'; 
?>
