<?php 
include 'header.phtml'; 
?>

<main>
	<form method="GET" action="resultList.php">
		<label for="research"></label>
		<input type="text" name="research" id="research" placeholder="Nouvelle recherche">
		<button>Recherchez</button>
	</form>
	<section>
		<h2> Votre panier</h2>

		<div class="panier">



			<table>
				<thead>
	                <tr>
	                    <th class="number">Produit</th>
	                    <th></th>
	                    <th>Quantité</th>
	                    <th class="number">Prix Unitaire</th>
	                    <th class="number">Prix Total</th>
	                    <th></th>
	                </tr>
            	</thead>

            	<tbody>
	  				<?php $totalTTC = 0?>
					<?php foreach ($products as $product): ?>
					<tr>
						<td><img src="<?= $product["photo"] ?>"></td>
						<td><p class="name"><?= $product["name"] ?></td>	
						
						<td class="number"><?= $product['price'] ?></td>
                    <td class="number"><?= $product['price'] * $product['quantity'] ?></td>
                    <td>
                        <button type="button" class="button button-cancel small btn-delete" title="Supprimer" data-id="<?= $product['id'] ?>">
                        <i class="fas fa-trash"></i>
                        </button>
                    </td>	
					</tr>	
					<?php $totalTTC += $product['price'] * $product['quantity'];?> 
					<?php endforeach; ?>

				</tbody>
			</table>
		</div>


	</section>
	
</main>

<?php 
include 'footer.phtml'; 
?>