<?php 
include 'header.phtml'; 
?>

<main>
	<form method="GET" action="resultList.php">
		<label for="research"></label>
		<input type="text" name="research" id="research" placeholder="Nouvelle recherche">
		<button>Recherchez</button>
	</form>
	<section>
		<h2> Détail du produit</h2>

		<div class="product">
			<table>
				<tr>
					<td> 
						<img class="productImage" src="<?= $product["photo"] ?>"> 
					</td>
					<td><p class="name"><?= $product["name"] ?></p>
						<p class="productPrice"><?= $product["price"] ?>€</p>
						<p class="quantity">Quantité en stock :<?= $product["quantity"] ?></p>
						<p class="description"><?= $product["description"] ?></p>	
						<a class ='addButton' href = "panier.php?id=<?= $product["id"] ?>"> Ajouter au panier </a>

					</td>
				</tr>
			</table>
		</div>
	

	</section>
	
</main>

<?php 
include 'footer.phtml'; 
?>