<?php 
include '../views/header.phtml'; 
?>

<main>
	<section>
		<h2> Résultat de votre recherche </h2>
		<?php 
			foreach ($productsSearch as $product): ?>
		<div class="product">
			<img src="<?= $product["photo"] ?>">	
			<p class="name"><?= $product["name"] ?></p>
			<p class="description"><?= $product["description"] ?></p>	
			<p class="price"><?= $product["price"] ?>€</p>
		</div>
		<?php 
			endforeach; ?>
	</section>
	<?php 
		if ($productsSearch == Array()){
			echo "Ce produit n'est pas en stock! <br>";
			echo "<a class ='mepButton' href = 'home.php'> Retournez à la recherche en cliquant ici </a>";
		} 
	?>

</main>

<?php 
include '../views/footer.phtml'; 
?>