<?php 
include 'header.phtml'; 
?>

<main>
	<form method="GET" action="resultList.php">
		<label for="research"></label>
		<input type="text" name="research" id="research" placeholder="Nouvelle recherche">
		<button>Recherchez</button>
	</form>
	<section>
		<h2> Résultat de votre recherche </h2>
		<?php foreach ($productsSearch as $product): ?>
		<div class="product">
			<img src="<?= $product["photo"] ?>">	
			<p class="name"><?= $product["name"] ?></p>
			<p class="description"><?= $product["description"] ?></p>	
			<p class="price"><?= $product["price"] ?>€</p>
			<a class ='detailButton' href = "product.php?id=<?= $product["id"] ?>"> Détail du produit </a>
		</div>
		<?php endforeach; ?>
	</section>
	<?php 
		if ($productsSearch == Array()){
			echo "Ce produit n'est pas en stock! <br>";
			echo "<a class ='mepButton' href = 'home.php'> Retournez à la recherche en cliquant ici </a>";
		} 
	?>

</main>

<?php 
include 'footer.phtml'; 
?>